module.exports = {
    // page
    billPage: '/bill',
    bookPage: '/book',
    paymentPage: '/payment',
    cardPage: '/card',
    setMealPage: '/setMeal',
    userPage: '/user',
    goodsPage: '/goods',
    storePage1: '/store/index',
    totalPage: '/total',
    staffPage: '/staff',
    staffPage1: '/staff/inlineStaff',
    otherPage: '/other',
    // api
    register: '/api/register',
    passwordChange: '/api/password_change',
    login: '/api/login',
    loginOut: '/api/out_login',
    // 员工
    getStaffList: '/api/get_staff',
    addStaff: '/api/add_staff',
    updateStaff: '/api/update_staff',
    deleteStaff: '/api/delete_staff',
    getStaffDetail: '/api/get_staff_detail',
    // 产品
    getGoodsList: '/api/get_goods',
    addGoods: '/api/add_goods',
    updateGoods: '/api/update_goods',
    deleteGoods: '/api/delete_goods',
    getGoodsDetail: '/api/get_goods_detail',
    // 用户
    getUserList: '/api/get_user',
    addUserList: '/api/add_user',
    updateUser: '/api/update_user',
    deleteUser: '/api/delete_user',
    // 卡类
    getCardList: '/api/get_card',
    addCard: '/api/add_card',
    updateCard: '/api/update_card',
    deleteCard:'/api/delete_card',
    // 账单
    getBillList: '/api/get_bill',
    addBill: '/api/add_bill',
    updateBill: '/api/update_bill',
    deleteBill:'/api/delete_bill',
    // 套餐
    getSetMeal: '/api/get_setmeal',
    addSetMeal:'/api/add_setmeal',
    updateSetMeal: '/api/update_setmeal',
    deleteSetMeal: '/api/delete_setmeal',
    // 预约
    getBookList: '/api/get_book',
    addBook: '/api/add_book',
    updateBook: '/api/update_book',
    deleteBook: '/api/delete_book',
    // 库存
    getStore: '/api/get_store',
    addStore: '/api/add_store',
    outStore: '/api/out_store',
    getJoinStore: '/api/get_joinstore',
    getOutStore: '/api/get_outstore',
    // 文档
    getDocument: '/api/get_document',
    addDocument: '/api/add_document',
    updateDocument: '/api/update_document',
    deleteDocument: '/api/delete_document',

    // 上传凭证接口
    getUploadToken: '/api/get_upload_token'
}